// Sertifikat yang umum dipakai di Indonesia
export type CertificateType =
  | 'SHM'           // Sertifikat Hak Milik
  | 'HGB'           // Hak Guna Bangunan
  | 'HGU'           // Hak Guna Usaha
  | 'Strata Title'  // Apartemen/Strata
  | 'Lainnya';

// Data rumah sesuai requirement
export type House = {
  id: number;

  // Kategori properti
  property_type: 'Cluster' | 'Apartemen' | 'Rumah Tinggal' | 'Townhouse';

  // Informasi utama
  title: string;
  description: string;

  // Lokasi & alamat
  address: string;
  sub_district: string;  // Kelurahan
  district: string;      // Kecamatan
  city: string;
  province: string;
  postal_code: string;
  latitude: number;
  longitude: number;

  // Spesifikasi fisik
  land_area: number;     // m2
  building_area: number; // m2
  bedrooms: number;
  bathrooms: number;
  floors: number;
  garage: number;
  year_built: number;

  // Harga & biaya
  price: number;             // total harga (Rp)
  price_per_sqm: number;     // Rp/m2 (bisa diisi hasil perhitungan)
  maintenance_fee: number;   // iuran bulanan (Rp)
  pbb_value: number;         // estimasi PBB per tahun (Rp)

  // Legalitas
  certificate_type: CertificateType;

  // Developer
  company_name: string;

  // Media
  image: string;
};

// Simpan array data rumah di sini (Contoh data lebih lengkap)
export const allHouses: House[] = [
  {
    id: 1,
    property_type: 'Cluster',
    title: 'Cluster Green Valley',
    description: 'Hunian asri dengan keamanan 24 jam dan taman bermain keluarga.',
    address: 'Jl. Boulevard Raya No. 1',
    sub_district: 'Pagedangan',
    district: 'Serpong',
    city: 'Tangerang Selatan',
    province: 'Banten',
    postal_code: '15339',
    latitude: -6.2945,
    longitude: 106.6542,
    land_area: 120,
    building_area: 90,
    bedrooms: 3,
    bathrooms: 2,
    floors: 2,
    garage: 1,
    year_built: 2022,
    price: 1500000000,
    price_per_sqm: Math.round(1500000000 / 90),
    maintenance_fee: 350000,
    pbb_value: 1800000,
    certificate_type: 'HGB',
    company_name: 'Sinarmas Land',
    image: '/rumah-1.jpg',
  },
  {
    id: 2,
    property_type: 'Rumah Tinggal',
    title: 'Rumah Klasik Menteng',
    description: 'Lokasi premium, desain klasik, halaman luas cocok untuk keluarga besar.',
    address: 'Jl. Teuku Umar No. 20',
    sub_district: 'Menteng',
    district: 'Menteng',
    city: 'Jakarta Pusat',
    province: 'DKI Jakarta',
    postal_code: '10310',
    latitude: -6.1978,
    longitude: 106.8320,
    land_area: 300,
    building_area: 250,
    bedrooms: 5,
    bathrooms: 4,
    floors: 2,
    garage: 2,
    year_built: 2018,
    price: 25000000000,
    price_per_sqm: Math.round(25000000000 / 250),
    maintenance_fee: 0,
    pbb_value: 25000000,
    certificate_type: 'SHM',
    company_name: 'Jaya Properti',
    image: '/rumah-2.jpg',
  },
  {
    id: 3,
    property_type: 'Apartemen',
    title: 'The Peak Apartment',
    description: 'Apartemen mewah dengan fasilitas lengkap: kolam renang, gym, dan sky lounge.',
    address: 'Jl. Sudirman Kav. 52-53',
    sub_district: 'Kebayoran Baru',
    district: 'Senayan',
    city: 'Jakarta Selatan',
    province: 'DKI Jakarta',
    postal_code: '12190',
    latitude: -6.2251,
    longitude: 106.8098,
    land_area: 0,
    building_area: 120,
    bedrooms: 2,
    bathrooms: 2,
    floors: 1,
    garage: 1,
    year_built: 2020,
    price: 4500000000,
    price_per_sqm: Math.round(4500000000 / 120),
    maintenance_fee: 1800000, // IPL
    pbb_value: 3500000,
    certificate_type: 'Strata Title',
    company_name: 'Agung Sedayu Group',
    image: '/rumah-3.jpg',
  },
  {
    id: 4,
    property_type: 'Cluster',
    title: 'Citra Garden Bintaro',
    description: 'Kawasan terpadu dekat pusat komersial dan tol.',
    address: 'Jl. Bintaro Utama Sektor 9',
    sub_district: 'Pondok Aren',
    district: 'Bintaro',
    city: 'Tangerang Selatan',
    province: 'Banten',
    postal_code: '15229',
    latitude: -6.2742,
    longitude: 106.7372,
    land_area: 90,
    building_area: 75,
    bedrooms: 3,
    bathrooms: 2,
    floors: 2,
    garage: 1,
    year_built: 2023,
    price: 1200000000,
    price_per_sqm: Math.round(1200000000 / 75),
    maintenance_fee: 300000,
    pbb_value: 1400000,
    certificate_type: 'HGB',
    company_name: 'Ciputra Development',
    image: '/rumah-4.jpg',
  },
  {
    id: 5,
    property_type: 'Rumah Tinggal',
    title: 'Pondok Indah Residence',
    description: 'Rumah modern minimalis di kawasan elit Pondok Indah.',
    address: 'Jl. Metro Pondok Indah',
    sub_district: 'Pondok Pinang',
    district: 'Kebayoran Lama',
    city: 'Jakarta Selatan',
    province: 'DKI Jakarta',
    postal_code: '12310',
    latitude: -6.2767,
    longitude: 106.7839,
    land_area: 250,
    building_area: 200,
    bedrooms: 4,
    bathrooms: 3,
    floors: 2,
    garage: 2,
    year_built: 2019,
    price: 15000000000,
    price_per_sqm: Math.round(15000000000 / 200),
    maintenance_fee: 0,
    pbb_value: 12000000,
    certificate_type: 'SHM',
    company_name: 'Pondok Indah Group',
    image: '/rumah-1.jpg',
  },
  {
    id: 6,
    property_type: 'Apartemen',
    title: 'Casa Grande Residence',
    description: 'Apartemen premium terhubung langsung ke mall dan perkantoran.',
    address: 'Jl. Casablanca Raya Kav. 88',
    sub_district: 'Menteng Dalam',
    district: 'Tebet',
    city: 'Jakarta Selatan',
    province: 'DKI Jakarta',
    postal_code: '12870',
    latitude: -6.2197,
    longitude: 106.8430,
    land_area: 0,
    building_area: 60,
    bedrooms: 1,
    bathrooms: 1,
    floors: 1,
    garage: 1,
    year_built: 2021,
    price: 2200000000,
    price_per_sqm: Math.round(2200000000 / 60),
    maintenance_fee: 1200000,
    pbb_value: 1800000,
    certificate_type: 'Strata Title',
    company_name: 'Pakuwon Group',
    image: '/rumah-2.jpg',
  },
  {
    id: 7,
    property_type: 'Cluster',
    title: 'Summarecon Serpong',
    description: 'Rumah keluarga dekat sekolah dan pusat kuliner.',
    address: 'Jl. Boulevard Gading Serpong',
    sub_district: 'Kelapa Dua',
    district: 'Kelapa Dua',
    city: 'Tangerang',
    province: 'Banten',
    postal_code: '15810',
    latitude: -6.2423,
    longitude: 106.6214,
    land_area: 180,
    building_area: 150,
    bedrooms: 4,
    bathrooms: 3,
    floors: 2,
    garage: 2,
    year_built: 2022,
    price: 3200000000,
    price_per_sqm: Math.round(3200000000 / 150),
    maintenance_fee: 400000,
    pbb_value: 3000000,
    certificate_type: 'HGB',
    company_name: 'Summarecon Agung',
    image: '/rumah-3.jpg',
  },
  {
    id: 8,
    property_type: 'Rumah Tinggal',
    title: 'Vila Modern Cisarua',
    description: 'Vila sejuk pegunungan dengan pemandangan hijau.',
    address: 'Jl. Raya Puncak KM 80',
    sub_district: 'Cisarua',
    district: 'Cisarua',
    city: 'Bogor',
    province: 'Jawa Barat',
    postal_code: '16750',
    latitude: -6.6610,
    longitude: 106.9340,
    land_area: 400,
    building_area: 180,
    bedrooms: 3,
    bathrooms: 2,
    floors: 1,
    garage: 1,
    year_built: 2017,
    price: 1800000000,
    price_per_sqm: Math.round(1800000000 / 180),
    maintenance_fee: 0,
    pbb_value: 1600000,
    certificate_type: 'SHM',
    company_name: 'Bogor Mountain Estate',
    image: '/rumah-4.jpg',
  },
  {
    id: 9,
    property_type: 'Townhouse',
    title: 'Kemang Village Townhouse',
    description: 'Townhouse eksklusif dengan akses langsung ke lifestyle mall.',
    address: 'Jl. Pangeran Antasari No. 36',
    sub_district: 'Bangun Cipta Sarana',
    district: 'Mampang Prapatan',
    city: 'Jakarta Selatan',
    province: 'DKI Jakarta',
    postal_code: '12150',
    latitude: -6.2609,
    longitude: 106.8141,
    land_area: 100,
    building_area: 160,
    bedrooms: 3,
    bathrooms: 3,
    floors: 3,
    garage: 1,
    year_built: 2015,
    price: 5500000000,
    price_per_sqm: Math.round(5500000000 / 160),
    maintenance_fee: 700000,
    pbb_value: 4200000,
    certificate_type: 'HGB',
    company_name: 'Lippo Karawaci',
    image: '/rumah-1.jpg',
  },
  {
    id: 10,
    property_type: 'Cluster',
    title: 'BSD City Cluster Avani',
    description: 'Cluster modern dengan club house dan danau buatan.',
    address: 'Jl. BSD Raya Barat',
    sub_district: 'Lengkong Kulon',
    district: 'Pagedangan',
    city: 'Tangerang Selatan',
    province: 'Banten',
    postal_code: '15331',
    latitude: -6.3042,
    longitude: 106.6520,
    land_area: 160,
    building_area: 130,
    bedrooms: 4,
    bathrooms: 3,
    floors: 2,
    garage: 2,
    year_built: 2020,
    price: 2800000000,
    price_per_sqm: Math.round(2800000000 / 130),
    maintenance_fee: 350000,
    pbb_value: 2600000,
    certificate_type: 'HGB',
    company_name: 'Sinar Mas Land',
    image: '/rumah-2.jpg',
  },
  {
    id: 11,
    property_type: 'Rumah Tinggal',
    title: 'Rumah Hijau Dago',
    description: 'Rumah artistik dengan banyak bukaan, sirkulasi udara optimal.',
    address: 'Jl. Dago Pakar Permai No. 7',
    sub_district: 'Ciburial',
    district: 'Cimenyan',
    city: 'Bandung',
    province: 'Jawa Barat',
    postal_code: '40198',
    latitude: -6.8541,
    longitude: 107.6476,
    land_area: 220,
    building_area: 180,
    bedrooms: 4,
    bathrooms: 3,
    floors: 2,
    garage: 2,
    year_built: 2016,
    price: 3500000000,
    price_per_sqm: Math.round(3500000000 / 180),
    maintenance_fee: 0,
    pbb_value: 2400000,
    certificate_type: 'SHM',
    company_name: 'Priangan Properti',
    image: '/rumah-3.jpg',
  },
  {
    id: 12,
    property_type: 'Apartemen',
    title: 'Anderson Tower - Pakuwon Mall',
    description: 'Unit high-rise dengan view kota, direct access ke mall.',
    address: 'Jl. Mayjen Yono Suwoyo No. 777',
    sub_district: 'Pradah Kalikendal',
    district: 'Dukuh Pakis',
    city: 'Surabaya',
    province: 'Jawa Timur',
    postal_code: '60216',
    latitude: -7.2903,
    longitude: 112.6802,
    land_area: 0,
    building_area: 45,
    bedrooms: 1,
    bathrooms: 1,
    floors: 1,
    garage: 1,
    year_built: 2021,
    price: 1100000000,
    price_per_sqm: Math.round(1100000000 / 45),
    maintenance_fee: 900000,
    pbb_value: 1200000,
    certificate_type: 'Strata Title',
    company_name: 'Pakuwon Group',
    image: '/rumah-4.jpg',
  },
];
